name: Doxygen
on:
  push:
    branches:
      - main

jobs:
  run-doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4

      - name: Deploy doc to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen/html
